sveltejs/sapper-template

templates/main.js
=> remove HMR stuff, let sapper inject it

webpack.client.config.js
Including commons chunk with some "aggressive" settings along with the `AggressiveSplittingPlugin` adds a considerable amount of savings to the base template. FWIW, we use the same `CommonsChunkPlugin` settings within Preact.
Previously, all Svelte helpers & all store & all etc were being included per route chunk, which wasn't necessary. This extracts everything & holds it within the `main` bundle.
Here are the before/afters:
***Before***:
***After***:
> The `AggressiveSplittingPlugin` isn't actually contributing to these savings, but it may help others in their larger apps.
Lastly, it seems like the `main.css` wasn't being extracted properly... now it is?
=> Add Commons Chunk 

README.md
#43 I'm actually not sure what the minimal files are
=> Readme: minimal set of files

app/template.html
Updating template comment that was referencing <:Head>
=> Update template.html comment referencing <:Head>

.gitignore
=> Ignore folders correctly

app/server.js, package.json
I would also suggest setting `maxAge` and `immutable` values (for production only), but leaving it out for the template may have been intentional.
_Closes #63_
=> Replace `serve-static` with `sirv`

app/server.js, package.json
Follow up to https://github.com/sveltejs/sapper/issues/316#issuecomment-414489763 and https://github.com/sveltejs/template/issues/10
=> Allow `sirv` to use "dev" mode

rollup/server.config.js
https://nodejs.org/dist/latest-v10.x/docs/api/modules.html#modules_module_builtinmodules
=> Accomodate < Node 9.3.0

app/server.js
=> Fix: Polka `.listen` 

app/server.js
=> (Rollup) Fix: Polka `.listen`

routes/_error.html
…lopment'
https://github.com/sveltejs/sapper-template/issues/73
=> _error.html renders `error.stack` when process.env.NODE_ENV === 'development'

README.md
=> Change yarn to npm in readme

README.md, src/template.html
This replaces references to the now non-existing app folder
=> Update doc & comments references to src folder

package_template.json, rollup.config.js
Super simple, I replaced the older `rollup-plugin-replace` with `@rollup/plugin-replace`
=> Switched to @rollup/plugin-replace

package_template.json, rollup.config.js
Simple update of rollup plugins, removing deprecated versions and adding new ones.
=> [update] - Replace rollup plugins with new ones

routes/blog/_posts.js
```diff
- <a href='https://gitter.im/sveltejs/svelte'>Gitter chatroom</a>
+ <a href='https://svelte.dev/chat'>Discord chatroom</a>
```
=> update page-transitions chat link to Discord

routes/blog/_posts.js
Reverts sveltejs/sapper-template#108
=> Revert "update page-transitions chat link to Discord"

package_template.json
Anyone trying Sapper is going to have a bad time rn. Until the roll up plugin is fixed, the fix posted here: https://github.com/sveltejs/sapper/issues/1151 is a good temp patch.
=> Temp fix for #212

package_template.json
Sorry my bad english.
fix [issue 207](https://github.com/sveltejs/sapper-template/issues/207).
[vulnerability](https://npmjs.com/advisories/1426)
I did not notice problems due to the replacement of rollup-plugin-terser from version 4.0.4 to version 5.3.0.
Error screenshot:
=> Vulnerability fix serialize-javascript issue 207

README.md
https://www.npmjs.com/package/vercel
=> update: vercel in readme

package_template.json, webpack.config.js
Mirrors https://github.com/sveltejs/sapper/pull/1262
=> Upgrade to sirv 1.0

rollup.config.js, webpack.config.js
=> Update rollup and webpack configs for svelte 3.17.1+

README.md
Mentioned the TypeScript conversion script in the README and made some stylistic changes to "Getting Started".
=> Mentioned TypeScript in the readme and made some stylistic changes

scripts/setupTypeScript.js
Fixes https://github.com/sveltejs/sapper-template/issues/292
=> Fix addition of preprocess to Rollup config in TypeScript setup script

README.md
ref: https://github.com/thgh/vercel-sapper/commit/c05eb2b32ca428e831abfd96a3a03723613995ef
=> Rename now-sapper to vercel-sapper

scripts/setupTypeScript.js
part of issue https://github.com/sveltejs/svelte-preprocess/issues/286
=> pass option sourceMap to sveltePreprocess

rollup.config.js
Looks like this got incorrectly overwritten in a copy paste.
=> Make process.browser false in server config

src/template.html, static/manifest.json
add new Lighthouse audits to pass PWA test.
More info:
https://web.dev/maskable-icon/
https://web.dev/apple-touch-icon/?utm_source=lighthouse&utm_medium=devtools
=> fix: lighthouse audit apple-icon and  maskable

src/ambient.d.ts
Fixes https://github.com/sveltejs/sapper-template/issues/290
=> fix: show ts error when importing images (#290)
