sveltejs/sapper-template

.travis.yml
appveyor.yml
package.json

Running `now` failed, because it was trying to install Cypress. This removes it and installs Cypress in CI instead

remove cypress from devDependencies and install in CI, so the app is deployable

---

.gitignore
app/service-worker.js
app/template.html
package.json
routes/5xx.html
routes/index.html
webpack/client.config.js
webpack/server.config.js
webpack/service-worker.config.js

General fixes and tweaks, some of which (e.g. `config.serviceworker`) will depend on Sapper 0.8

Updates for 0.8

---

webpack.client.config.js

This removes roughly 1.63KB of the unnecessary "process" module, assuming the user is using idioms like `process.browser` and `process.env.NODE_ENV`.

Optimize Webpack "process" env

---

README.md

Remove license section as mentioned in https://github.com/sveltejs/sapper-template/issues/28, plus the link is broken.

Remove license section

---

app/service-worker.js

The previous implementation tried to cache `only-if-cached` by changing
request mode but it doesn't work because the property is readonly.
However, caching responses cached with HTTP Cache again with Cache API
does not make sense anyway. Just do not cache it, and leave it to HTTP
cache.
Resolves https://github.com/sveltejs/sapper-template/issues/34#issuecomment-401404754. I made this change according to WHATWG Fetch Standard. Please tell me if you found something incompatible with the specification.

Do not cache with Cache API if cache mode is only-if-cached

---

README.md

`sveltejs/sapper-template-rollup` doesn't exist, but `sveltejs/sapper-template` has a `rollup` branch. Fixed the docs to refer to the branch since I assume that was the intent all along.

docs: fix git specifier for rollup version

---

rollup.config.js

experimentalCodeSplitting options no longer needed with Rollup 1.0+ (https://github.com/rollup/rollup/releases/tag/v1.0.0)

removed experimentalCodeSplitting options

---

src/service-worker.js

This is the sister PR to https://github.com/sveltejs/sapper/pull/525. All it does is change a code comment to reference `service-worker-index.html`. The old `index.html` hasn't worked for a while anyway.

use service-worker-index.html in commented code

---

package_template.json

From v0.17.0 onwards, [Sapper uses cheap-watch instead of chokidar.](https://github.com/sveltejs/sapper/pull/365)
Live reloading works when you create a project with `npx degit sveltejs/sapper-template#rollup` and remove chokidar from the resulting *package.json* before installing. Nothing else in the project depends on chokidar.
Closes https://github.com/sveltejs/sapper-template/issues/129

Remove chokidar devDependency

---

rollup.config.js

Resolves #145. It's ugly, but I am almost positive that this will solve infinitely more problems than it causes.

rollup: suppress `@sapper` circular dependency warnings

---

rollup.config.js

I'm sick of debugging bundler problems because of Axios. 
This adds the `browser:true` to the rollup-plugin-node-resolve options for the client build only. This should be useful for any libraries that specify a separate browser build using the browser field in `package.json`. I don't think it would cause any problems (it should be ignored if the browser field isn't used).
The webpack client build already resolves the browser field, if my naive reading of the webpack config is correct.
If it will cause problems that you know of, feel free to decline and I'll go back to my life of misery.

Add browser:true to rollup-plugin-node-resolve for client build.

---

src/components/Nav.svelte

Simply swapped the Nav component's `selected` link class assignment from a ternary expression to the class directive.

Replace ternary assignment with class directive

---

src/template.html

I got warning in Visual Studio Code saying
```
The head element represents a collection of metadata for the Document.
A11y: <html> element should have a lang attributesvelte(a11y-missing-attribute)
```
And this fix the problem

Add lang attribute to html template

---

package_template.json
rollup.config.js

https://github.com/rollup/plugins/pull/99 introduced a change to how `dedupe` works. It now matches just the package name, so we can use the array syntax, which is a bit less confusing.

use improved dedupe in @rollup/plugin-node-resolve@7

---

README.md

This PR updates the deployment section to advise the use of `now-sapper` for deploying to ZEIT Now when using SSR.
@antony please let me know your thoughts, we can iterate if required 👍

Update Deployment Section

---

src/routes/blog/_posts.js

Hello! I noticed in the blog docs post titled `How is Sapper different from Next.js?`
the second bullet says this
```
For example, the page you're looking at right now is src/routes/blog/[slug].html
```
and would like to change it to 
```
For example, the page you're looking at right now is src/routes/blog/[slug].svelte
```

Update blog docs url path from html to svelte

---

src/template.html

Including `crossorigin` attribute on manifest link helps us to avoid additional TLS connection. Streamlines loading of manifest.json and app icons.
Ref: 
https://twitter.com/TimVereecke/status/1225547620791341062
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin#Example_Webmanifest_with_credentials
Trims a few hundred milliseconds off request over 3G:
**Before:** 
**After:**
Worth doing some further testing, but may improve boot-up time of app when running as a PWA?

Add manifest crossorigin="use-credentials"

---

src/components/Nav.svelte

Preserves the visual styling and adds hints to AT. For example NVDA will now read
```diff
home
-visited  link
+visited  link  current page
blog
link
about
link
blog
link
home
-visited  link
+visited  link  current page
```
when tabbing through the list.
[`aria-current` spec](https://www.w3.org/TR/wai-aria-1.1/#aria-current)

feat: Use aria-current instead of visual only indicator

---

package_template.json
rollup.config.js

This is not ready for merging until an issue for `@rollup/plugin-commonjs` is fixed, which should be any day: https://github.com/rollup/plugins/issues/304
Before merging this PR should update that dependency to the fix first.
Relevant Sapper issue: https://github.com/sveltejs/sapper/issues/1151
Will also fix: sveltejs/sapper-template#218

[Sapper #1151] Updated rollup dependencies

---

rollup.config.js

According to the comment in https://github.com/sveltejs/sapper-template/issues/206#issuecomment-596485705 this code is no longer used after we've upgraded to Rollup 2, which happened awhile ago

Remove unused fallback

---

webpack.config.js

This will prevent confusion like [this one](https://stackoverflow.com/q/61988779/3468917) where users want to change `mode` to 'development' by changing the top-level `const mode = process.env.NODE_ENV;` only to realize it has no effect in the `server` and `serviceworker` configurations.

use 'mode' consistently in webpack config

---

rollup.config.js

In https://github.com/sveltejs/sapper/pull/1344 we decided to implement in a way that would create warnings and then silence them in the template

Silence preload export warnings related to TypeScript support

---

scripts/setupTypeScriptRollup.js
src/routes/blog/[slug].svelte
src/routes/blog/index.svelte

Continued pull request of https://github.com/sveltejs/sapper-template/pull/252.

Rollup TypeScript support

---

scripts/setupTypeScriptRollup.js

Made the `setupTypeScriptRollup` safer to run in case the project already has changes:
- Never overwrite any existing files
- If a file is missing, warn and continue (as opposed to halting)
- Do not corrupt files if run twice
- Warn if the lines to be changed could not be found, e.g. if a user has modified `rollup.config.js` in unexpected ways.
Also refactored it a bit by breaking it up into functions.
I tested the changes by creating the template project, running the script and the dev server. Then I ran the script again and verified that for each file it said the changes had already been applied and starting the dev server.

Refactored setupTypeScript script

---

scripts/setupTypeScriptRollup.js

When running this script, the modified `rollup.config.js` file becomes:
```javascript
[...]
import babel from '@rollup/plugin-babel';
import { terser } from 'rollup-plugin-terser';
import sveltePreprocess from 'svelte-preprocess';
import typescript from '@rollup/plugin-typescript';import config from 'sapper/config/rollup.js';
import pkg from './package.json';
[...]
```
Thus, a new line should be added after the inserted import statements.

Add new line after inserted import statements

---

_template/create-branches.sh

Remove "Rollup" from setupTypeScript script name in rollup branch and remove it in webpack branch.
Fixes #268 
Blocks #1557 and #267

Remove "Rollup" from setupTypeScript script name in rollup branch

---

scripts/setupTypeScriptRollup.js

After looking at sveltejs/sapper#1583 and being quite confused myself as to how the `@sapper` dependencies are resolved, added that information to the message in the `setupTypeScript` script.

Point out that `npm run build` is required for @sapper imports

---

scripts/setupTypeScript.js

We need to double backslashes in template literals.

Preserve backslashes in template literals

---

webpack.config.js

Per @Conduitry's suggestion in https://github.com/sveltejs/sapper-template/pull/248#discussion_r505688786
It looks like this is now the config demonstrated in the webpack docs: https://webpack.js.org/loaders/file-loader/#getting-started
It looks like there's a separate inline svg loader, which is probably why they don't demonstrate that anymore

Update webpack file-loader config

---

src/ambient.d.ts

This fixes #281 or at least it fixes `svelte-check`.
The import is still reported as an error in VSCode but I suspect that is the same thing as sveltejs/language-tools#610
(There are plenty more file types we theoretically could add; not sure if it makes sense to add all of them from the beginning)

Added an ambient type declaration for allowing image imports

---

README.md
src/routes/index.svelte

To explain to users the outcome of #229 I added a comment to the import statement and updated the README.
As usual I couldn't keep from also doing some changes to adjacent sections in the README.

Documented the importing of images from node_modules

---

package_template.json
rollup.config.js

When starting a new sapper app with with rollup using this template you encounter a warning line 
```bash
@rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
```
I'm open this PR to fix it

fix: Rollup replace plugin warnings

---

package_template.json
webpack.config.js

I'm not sure about HMR working out of the box, because it may need Webpack HMR plugin or dev server, which I'm not sure sapper provides. :thinking: 
Will add some commits later.
Fixes #307

Upgrade svelte-loader to 3.0.0

---

scripts/setupTypeScript.js

I tried to build the webpack template earlier today and noticed it was breaking.
I think it's because the script to convert it to typescript is inserting `sveltePreprocess` in the wrong position.
This PR should fix that 👍

Fix TS script for webpack
